FROM nvcr.io/nvidia/tritonserver:25.08-py3

WORKDIR /

COPY model_repository /models

EXPOSE 8000
EXPOSE 8001
EXPOSE 8002

CMD ["tritonserver", \
     "--model-repository=/models", \
     "--log-verbose=1", \
     "--strict-model-config=false"]